Test de k-médioides sur séries temporelles (Nada)

In [80]:
from scipy.spatial import distance
import numpy as np
import math

#mesure de similarité dtw entre deux séries temporelles. x = un pixel sur un intervalle de temps
def dtw(x, x_prime):
  R=np.zeros((len(x),len(x_prime)))
  for i in range(len(x)):
    for j in range(len(x_prime)):
      R[i, j] = distance.euclidean(x[i], x_prime[j]) ** 2
      if i > 0 or j > 0:
        R[i, j] += min(
          R[i-1, j  ] if i > 0             else math.inf,
          R[i  , j-1] if j > 0             else math.inf,
          R[i-1, j-1] if (i > 0 and j > 0) else math.inf
        )

  return R[-1, -1] ** (1/2)



In [91]:


#génération des matrices : 
data=np.random.rand(5)
sequence1 = np.random.rand(5,1)
sequence2 = np.random.rand(5,1)
sequence3 = np.random.rand(5,1)
sequence4= np.random.rand(5,1)

print(dtw(sequence1,sequence2))
print(sequence1.shape)

0.4905886158586988
(5, 1)


In [92]:
# Regrouper les séquences dans une liste
data = [sequence1, sequence2, sequence3, sequence4]
data=np.array(data)

#def k_medoids_clustering(data, k, max_iterations=100):
    # Sélectionner les k médioides initiaux
 #   means = np.random.choice(len(data), k, replace=False)

  #  for _ in range(max_iterations):
        # Affectation des points aux means
   #     clusters = [[] for _ in range(k)]
    #    for i, point in enumerate(data):
     #       distances = [dtw(data[m], point)[0] for m in means]
      #      cluster_assignment = np.argmin(distances)
       #     clusters[cluster_assignment].append(i)

        # Mise à jour des means
        #for i in range(k):
         #   cluster_indices = clusters[i]
          #  cluster_points = data[cluster_indices]
           # means_index = min([(idx, np.sum([dtw(data[m], data[idx])[0] for m in cluster_indices]))
            #                    for idx in cluster_indices], key=lambda x: x[1])[0]
            #medoids[i] = medoid_index

        # Convertir les indices des clusters en points réels
    #clustered_points = [[data[i] for i in cluster_indices] for cluster_indices in clusters]

    #return clustered_points, medoids


#result_clustered_points,results_medoids=k_medoids_clustering(data,k=3)
#print(data)

# Afficher les points dans chaque cluster
#for i, cluster in enumerate(result_clustered_points):
 #   print(f"Cluster {i + 1}: {cluster}")

In [104]:
import numpy as np
 
#Function to implement steps given in previous section
def kmeans(x,k, no_of_iterations):
    idx = np.random.choice(len(x), k, replace=False)
    
    #Randomly choosing Centroids 
    centroids = x[idx, :] #Step 1
     
    #finding the distance between centroids and all the data points
    distances=np.zeros((len(x),k))
    for i in range(len(x)):
            for j in range(len(centroids)):
                    distances[i,j]=(dtw(x[i], centroids[j])) #Step 2
     
    #Centroid with the minimum Distance
    points = np.array([np.argmin(i) for i in distances]) #Step 3
     
    # Repeating the above steps for a defined number of iterations
    # Step 4
    for _ in range(no_of_iterations):
        centroids = []
        for idx in range(k):
            # Updating Centroids by taking mean of Cluster it belongs to
            temp_cent = x[points == idx].mean(axis=0)
            centroids.append(temp_cent)

        centroids = np.vstack(centroids)  # Updated Centroids
    
    distances=np.zeros((len(x),k))
    for i in range(len(x)):
            for j in range(len(centroids)):
                    distances[i,j]=(dtw(x[i], centroids[j])) 

    points = np.array([np.argmin(i) for i in distances])
         
    return points 

In [112]:
# Function to implement steps given in the previous section
def kmeans2(x, k, no_of_iterations):
    idx = np.random.choice(len(x), k, replace=False)

    # Randomly choosing Centroids
    centroids = x[idx, :]  # Step 1

    for _ in range(no_of_iterations):
        # Finding the distance between centroids and all the data points
        distances = np.zeros((len(x), k))
        for i in range(len(x)):
            for j in range(len(centroids)):
                distances[i, j] = dtw(x[i], centroids[j])  # Step 2

        # Centroid with the minimum Distance
        points = np.array([np.argmin(i) for i in distances])  # Step 3

        # Updating Centroids by taking the mean of the Cluster it belongs to
        centroids = np.array([x[points == idx].mean(axis=0) for idx in range(k)])  # Updated Centroids

    return centroids, points


result_clusters,results_points=kmeans2(data,3,2)
# Afficher les points dans chaque cluster
for i, cluster in enumerate(result_clusters):
    print(f"Cluster {i + 1}: {cluster}")





Cluster 1: [[0.3588848 ]
 [0.18152498]
 [0.51610303]
 [0.05617149]
 [0.97590365]]
Cluster 2: [[0.11386539]
 [0.56628313]
 [0.46187986]
 [0.881758  ]
 [0.9667312 ]]
Cluster 3: [[0.46070698]
 [0.52914999]
 [0.95302865]
 [0.29233359]
 [0.60846228]]


In [113]:
print(data)

[[[0.11386539]
  [0.56628313]
  [0.46187986]
  [0.881758  ]
  [0.9667312 ]]

 [[0.3588848 ]
  [0.18152498]
  [0.51610303]
  [0.05617149]
  [0.97590365]]

 [[0.12913008]
  [0.87247422]
  [0.91455154]
  [0.29801884]
  [0.51372084]]

 [[0.79228388]
  [0.18582576]
  [0.99150576]
  [0.28664834]
  [0.70320373]]]
